---
title: "Exploratory Data Analysis Project 1 Codebook"
author: "Michael G Harpole"
date: "`r Sys.Date()`"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

# Plot 1

This plot is a histogram which shows the global active power in kilowats. Components of the histogram:

* color of the bins are red. 
* y axis label is frequency. 
* x axis label is Global Active Power (kilowats). 
* main title is Global Active Power

```{r, plot 1,warning=FALSE}
myFiles <- list.files(pattern="*.txt")
myFiles
myData <- read_delim(myFiles[1],na="?",show_col_types = FALSE) %>% 
  mutate(Date=lubridate::dmy(Date)) %>% 
  filter(between(Date, as.Date('2007-02-01'), as.Date('2007-02-02')))
# only want dates between 2007-02-01 and 2007-02-02
summary(myData)
head(myData)
names(myData)
hist(myData$Global_active_power,col = "red",
     xlab = "Global Active Power (kilowats)",
     main="Global Active Power")
dev.copy(png,"plot1.png")
dev.off()
```
